export enum SettingEnum {
  MINS_BETWEEN_LOCATION_HEARTBEATS = "MINS_BETWEEN_LOCATION_HEARTBEATS",
  COOL_OFF_SECONDS_BTWN_DIFF_ROUTE_SCANS = "COOL_OFF_SECONDS_BTWN_DIFF_ROUTE_SCANS",
  DEFAULT_GREETING = "DEFAULT_GREETING",
}
