export enum SettingEnum {
  MINS_BETWEEN_LOCATION_HEARTBEATS = "MINS_BETWEEN_LOCATION_HEARTBEATS",
  COOL_OFF_SECONDS_BTWN_DIFF_ROUTE_SCANS = "COOL_OFF_SECONDS_BTWN_DIFF_ROUTE_SCANS",
  UPDATE_DOC_STATUS_TO_ERP = "UPDATE_DOC_STATUS_TO_ERP",
  SEND_TRACKING_SMS = "SEND_TRACKING_SMS",
  DEFAULT_GREETING = "DEFAULT_GREETING",
}
