export class GlobalConstants {
  static readonly SMS_GENERATE_OTP_TEMPLATE =
    "https://2factor.in/API/V1/{apikey}/SMS/{mobilePhone}/AUTOGEN/{otpTemplateName}";
  static readonly SMS_VALIDATE_OTP_TEMPLATE =
    "https://2factor.in/API/V1/{apikey}/SMS/VERIFY3/{mobilePhone}/{otp}";
  static readonly SEND_SMS_URL_TEMPLATE =
    "https://2factor.in/API/R1/?module=TRANS_SMS&apikey={apikey}&to={recipientMobileNumber}&from=BTBLZR&templatename={smsTemplateName}";
  static readonly SMS_OTP_TEMPLATE = "PHARMA_OTP_V6";

  // ERP API Configuration
  static readonly ERP_API_BASE_URL = "https://sit-api.1c2.in:4431/delivery";
  static readonly ERP_API_PROD_CODE = "DEV-DELCONN";
  static readonly ERP_API_TOKEN = "f1e069787ece74";
  static readonly ERP_API_HEADERS = {
    "x-api-prod-code": "DEV-DELCONN",
    "x-api-token": "f1e069787ece74",
  };
  static readonly FALLBACK_LOCATION_HEARTBEAT_FREQUENCY_IN_SECONDS = 60;
  static readonly FALLBACK_SCAN_ROUTE_TIMEOUT_SECONDS = 10;

  static readonly MOCK_CUSTOMER_PREFIX = "MOCKCUST";

  static readonly NUM_BARCODES_IN_PDF = 12;

  // Document grouping constants
  static readonly DIRECT_DELIVERIES_GROUP_HEADING = "Direct Deliveries";

  // Database backup constants
  static readonly MAX_BACKUP_FILES = 30;
  static readonly BACKUP_BUCKET_NAME = "pharmatracker-db-dump";
  static readonly AWS_REGION = "ap-south-1"; // Mumbai
  static readonly RESTORE_PASSKEY = "4321"; // Change this to a secure value
  static readonly BACKUP_RECENT_CHECK_MINUTES = 5;

  // Customer data with cities, pincodes, and routes (100 customers)
  static readonly CUSTOMERS = [
    // Route 1 - Ernakulam
    {
      docId: ``,
      id: `${GlobalConstants.MOCK_CUSTOMER_PREFIX}001`,
      name: "ABC Pharmaceuticals",
      address: "123 Business Park",
      city: "Ernakulam",
      pincode: "682001",
      phone: "1234567890",
      route: "Route 1",
    },
    {
      id: `${GlobalConstants.MOCK_CUSTOMER_PREFIX}002`,
      name: "Ernakulam Medical Center",
      address: "456 MG Road",
      city: "Ernakulam",
      pincode: "682001",
      phone: "2345678901",
      route: "Route 1",
    },
    {
      id: `${GlobalConstants.MOCK_CUSTOMER_PREFIX}003`,
      name: "Kochi Pharma Ltd",
      address: "789 Marine Drive",
      city: "Ernakulam",
      pincode: "682001",
      phone: "3456789012",
      route: "Route 1",
    },
    {
      id: `${GlobalConstants.MOCK_CUSTOMER_PREFIX}004`,
      name: "Fort Kochi Hospital",
      address: "321 Fort Area",
      city: "Ernakulam",
      pincode: "682001",
      phone: "4567890123",
      route: "Route 1",
    },
    {
      id: `${GlobalConstants.MOCK_CUSTOMER_PREFIX}005`,
      name: "Jubilee Medical Store",
      address: "654 Broadway",
      city: "Ernakulam",
      pincode: "682001",
      phone: "5678901234",
      route: "Route 1",
    },
    {
      id: `${GlobalConstants.MOCK_CUSTOMER_PREFIX}006`,
      name: "Lulu Pharmacy",
      address: "987 Edappally",
      city: "Ernakulam",
      pincode: "682001",
      phone: "1234567891",
      route: "Route 1",
    },
    {
      id: `${GlobalConstants.MOCK_CUSTOMER_PREFIX}007`,
      name: "Kakkanad Health Center",
      address: "147 Infopark",
      city: "Ernakulam",
      pincode: "682001",
      phone: "2345678902",
      route: "Route 1",
    },
    {
      id: `${GlobalConstants.MOCK_CUSTOMER_PREFIX}008`,
      name: "Vytilla Medical Hub",
      address: "258 Vytilla",
      city: "Ernakulam",
      pincode: "682001",
      phone: "3456789013",
      route: "Route 1",
    },
    {
      id: `${GlobalConstants.MOCK_CUSTOMER_PREFIX}009`,
      name: "Aluva General Hospital",
      address: "369 Aluva",
      city: "Ernakulam",
      pincode: "682001",
      phone: "4567890124",
      route: "Route 1",
    },
    {
      id: `${GlobalConstants.MOCK_CUSTOMER_PREFIX}010`,
      name: "Perumbavoor Clinic",
      address: "741 Perumbavoor",
      city: "Ernakulam",
      pincode: "682001",
      phone: "5678901235",
      route: "Route 1",
    },
    {
      id: `${GlobalConstants.MOCK_CUSTOMER_PREFIX}011`,
      name: "Kochi Central Pharmacy",
      address: "852 MG Road",
      city: "Ernakulam",
      pincode: "682001",
      phone: "1234567892",
      route: "Route 1",
    },
    {
      id: `${GlobalConstants.MOCK_CUSTOMER_PREFIX}012`,
      name: "Marine Drive Medical",
      address: "963 Waterfront",
      city: "Ernakulam",
      pincode: "682001",
      phone: "2345678903",
      route: "Route 1",
    },
    {
      id: `${GlobalConstants.MOCK_CUSTOMER_PREFIX}013`,
      name: "Fort Kochi Pharmacy",
      address: "147 Heritage Road",
      city: "Ernakulam",
      pincode: "682001",
      phone: "3456789014",
      route: "Route 1",
    },
    {
      id: `${GlobalConstants.MOCK_CUSTOMER_PREFIX}014`,
      name: "Broadway Health Center",
      address: "258 Commercial Street",
      city: "Ernakulam",
      pincode: "682001",
      phone: "4567890125",
      route: "Route 1",
    },
    {
      id: `${GlobalConstants.MOCK_CUSTOMER_PREFIX}015`,
      name: "Edappally Medical Store",
      address: "369 Highway Road",
      city: "Ernakulam",
      pincode: "682001",
      phone: "5678901236",
      route: "Route 1",
    },
    {
      id: `${GlobalConstants.MOCK_CUSTOMER_PREFIX}016`,
      name: "Infopark Clinic",
      address: "741 Tech Park",
      city: "Ernakulam",
      pincode: "682001",
      phone: "1234567893",
      route: "Route 1",
    },
    {
      id: `${GlobalConstants.MOCK_CUSTOMER_PREFIX}017`,
      name: "Kakkanad Pharmacy",
      address: "852 IT Hub",
      city: "Ernakulam",
      pincode: "682001",
      phone: "2345678904",
      route: "Route 1",
    },
    {
      id: `${GlobalConstants.MOCK_CUSTOMER_PREFIX}018`,
      name: "Aluva Medical Center",
      address: "963 Railway Station",
      city: "Ernakulam",
      pincode: "682001",
      phone: "3456789015",
      route: "Route 1",
    },
    {
      id: `${GlobalConstants.MOCK_CUSTOMER_PREFIX}019`,
      name: "Angamaly Health Store",
      address: "147 Airport Road",
      city: "Ernakulam",
      pincode: "682001",
      phone: "4567890126",
      route: "Route 1",
    },
    {
      id: `${GlobalConstants.MOCK_CUSTOMER_PREFIX}020`,
      name: "Perumbavoor Medical",
      address: "258 Industrial Area",
      city: "Ernakulam",
      pincode: "682001",
      phone: "5678901237",
      route: "Route 1",
    },

    // Route 2 - Kodakara & Thrissur
    {
      id: `${GlobalConstants.MOCK_CUSTOMER_PREFIX}021`,
      name: "XYZ Medical Center",
      address: "456 Health Street",
      city: "Kodakara",
      pincode: "680684",
      phone: "1234567894",
      route: "Route 2",
    },
    {
      id: `${GlobalConstants.MOCK_CUSTOMER_PREFIX}022`,
      name: "Kodakara Pharmacy",
      address: "123 Main Road",
      city: "Kodakara",
      pincode: "680684",
      phone: "1234567894",
      route: "Route 2",
    },
    {
      id: `${GlobalConstants.MOCK_CUSTOMER_PREFIX}023`,
      name: "MediCorp Ltd",
      address: "789 Medical Avenue",
      city: "Thrissur",
      pincode: "680001",
      phone: "2345678905",
      route: "Route 2",
    },
    {
      id: `${GlobalConstants.MOCK_CUSTOMER_PREFIX}024`,
      name: "Thrissur Medical College",
      address: "321 College Road",
      city: "Thrissur",
      pincode: "680001",
      phone: "2345678905",
      route: "Route 2",
    },
    {
      id: `${GlobalConstants.MOCK_CUSTOMER_PREFIX}025`,
      name: "Guruvayur Hospital",
      address: "654 Temple Road",
      city: "Thrissur",
      pincode: "680001",
      phone: "2345678905",
      route: "Route 2",
    },
    {
      id: `${GlobalConstants.MOCK_CUSTOMER_PREFIX}026`,
      name: "Chalakudy Medical Center",
      address: "987 NH47",
      city: "Thrissur",
      pincode: "680001",
      phone: "2345678905",
      route: "Route 2",
    },
    {
      id: `${GlobalConstants.MOCK_CUSTOMER_PREFIX}027`,
      name: "Irinjalakuda Clinic",
      address: "147 Railway Station",
      city: "Thrissur",
      pincode: "680001",
      phone: "2345678905",
      route: "Route 2",
    },
    {
      id: `${GlobalConstants.MOCK_CUSTOMER_PREFIX}028`,
      name: "Wadakkanchery Pharmacy",
      address: "258 Market Road",
      city: "Thrissur",
      pincode: "680001",
      phone: "2345678905",
      route: "Route 2",
    },
    {
      id: `${GlobalConstants.MOCK_CUSTOMER_PREFIX}029`,
      name: "Kodungallur Medical Store",
      address: "369 Beach Road",
      city: "Thrissur",
      pincode: "680001",
      phone: "2345678905",
      route: "Route 2",
    },
    {
      id: `${GlobalConstants.MOCK_CUSTOMER_PREFIX}030`,
      name: "Kunnamkulam Health Center",
      address: "741 Bus Stand",
      city: "Thrissur",
      pincode: "680001",
      phone: "2345678905",
      route: "Route 2",
    },
    {
      id: `${GlobalConstants.MOCK_CUSTOMER_PREFIX}031`,
      name: "Kodakara Central Medical",
      address: "852 Main Street",
      city: "Kodakara",
      pincode: "680684",
      phone: "1234567894",
      route: "Route 2",
    },
    {
      id: `${GlobalConstants.MOCK_CUSTOMER_PREFIX}032`,
      name: "Thrissur City Pharmacy",
      address: "963 Round Road",
      city: "Thrissur",
      pincode: "680001",
      phone: "2345678905",
      route: "Route 2",
    },
    {
      id: `${GlobalConstants.MOCK_CUSTOMER_PREFIX}033`,
      name: "MediCorp Central",
      address: "147 Medical Avenue",
      city: "Thrissur",
      pincode: "680001",
      phone: "2345678905",
      route: "Route 2",
    },
    {
      id: `${GlobalConstants.MOCK_CUSTOMER_PREFIX}034`,
      name: "Thrissur General Hospital",
      address: "258 Hospital Road",
      city: "Thrissur",
      pincode: "680001",
      phone: "2345678905",
      route: "Route 2",
    },
    {
      id: `${GlobalConstants.MOCK_CUSTOMER_PREFIX}035`,
      name: "Guruvayur Medical Store",
      address: "369 Temple Street",
      city: "Thrissur",
      pincode: "680001",
      phone: "2345678905",
      route: "Route 2",
    },
    {
      id: `${GlobalConstants.MOCK_CUSTOMER_PREFIX}036`,
      name: "Chalakudy Central Clinic",
      address: "741 NH47 Road",
      city: "Thrissur",
      pincode: "680001",
      phone: "2345678905",
      route: "Route 2",
    },
    {
      id: `${GlobalConstants.MOCK_CUSTOMER_PREFIX}037`,
      name: "Irinjalakuda Health Center",
      address: "852 Railway Station",
      city: "Thrissur",
      pincode: "680001",
      phone: "2345678905",
      route: "Route 2",
    },
    {
      id: `${GlobalConstants.MOCK_CUSTOMER_PREFIX}038`,
      name: "Wadakkanchery Medical",
      address: "963 Market Road",
      city: "Thrissur",
      pincode: "680001",
      phone: "2345678905",
      route: "Route 2",
    },
    {
      id: `${GlobalConstants.MOCK_CUSTOMER_PREFIX}039`,
      name: "Kodungallur Central",
      address: "147 Beach Road",
      city: "Thrissur",
      pincode: "680001",
      phone: "2345678905",
      route: "Route 2",
    },
    {
      id: `${GlobalConstants.MOCK_CUSTOMER_PREFIX}040`,
      name: "Kunnamkulam Central",
      address: "258 Bus Stand",
      city: "Thrissur",
      pincode: "680001",
      phone: "2345678905",
      route: "Route 2",
    },

    // Route 3 - Alleppey & Cherthala
    {
      id: `${GlobalConstants.MOCK_CUSTOMER_PREFIX}041`,
      name: "HealthPlus Inc",
      address: "321 Wellness Road",
      city: "Alleppey",
      pincode: "688001",
      phone: "3456789016",
      route: "Route 3",
    },
    {
      id: `${GlobalConstants.MOCK_CUSTOMER_PREFIX}042`,
      name: "Alleppey Medical Center",
      address: "456 Beach Road",
      city: "Alleppey",
      pincode: "688001",
      phone: "3456789016",
      route: "Route 3",
    },
    {
      id: `${GlobalConstants.MOCK_CUSTOMER_PREFIX}043`,
      name: "Backwater Hospital",
      address: "789 Canal Road",
      city: "Alleppey",
      pincode: "688001",
      phone: "3456789016",
      route: "Route 3",
    },
    {
      id: `${GlobalConstants.MOCK_CUSTOMER_PREFIX}044`,
      name: "Alappuzha General",
      address: "123 Market Road",
      city: "Alleppey",
      pincode: "688001",
      phone: "3456789016",
      route: "Route 3",
    },
    {
      id: `${GlobalConstants.MOCK_CUSTOMER_PREFIX}045`,
      name: "Pharma Solutions",
      address: "654 Medicine Lane",
      city: "Cherthala",
      pincode: "688524",
      phone: "4567890127",
      route: "Route 3",
    },
    {
      id: `${GlobalConstants.MOCK_CUSTOMER_PREFIX}046`,
      name: "Cherthala Medical Store",
      address: "987 Main Street",
      city: "Cherthala",
      pincode: "688524",
      phone: "4567890127",
      route: "Route 3",
    },
    {
      id: `${GlobalConstants.MOCK_CUSTOMER_PREFIX}047`,
      name: "Kayamkulam Hospital",
      address: "147 Railway Road",
      city: "Alleppey",
      pincode: "688001",
      phone: "3456789016",
      route: "Route 3",
    },
    {
      id: `${GlobalConstants.MOCK_CUSTOMER_PREFIX}048`,
      name: "Haripad Clinic",
      address: "258 Temple Road",
      city: "Alleppey",
      pincode: "688001",
      phone: "3456789016",
      route: "Route 3",
    },
    {
      id: `${GlobalConstants.MOCK_CUSTOMER_PREFIX}049`,
      name: "Mavelikkara Pharmacy",
      address: "369 Market Street",
      city: "Alleppey",
      pincode: "688001",
      phone: "3456789016",
      route: "Route 3",
    },
    {
      id: `${GlobalConstants.MOCK_CUSTOMER_PREFIX}050`,
      name: "Chengannur Medical Center",
      address: "741 Bus Stand Road",
      city: "Alleppey",
      pincode: "688001",
      phone: "3456789016",
      route: "Route 3",
    },
    {
      id: `${GlobalConstants.MOCK_CUSTOMER_PREFIX}051`,
      name: "HealthPlus Central",
      address: "852 Wellness Road",
      city: "Alleppey",
      pincode: "688001",
      phone: "3456789016",
      route: "Route 3",
    },
    {
      id: `${GlobalConstants.MOCK_CUSTOMER_PREFIX}052`,
      name: "Alleppey City Medical",
      address: "963 Beach Road",
      city: "Alleppey",
      pincode: "688001",
      phone: "3456789016",
      route: "Route 3",
    },
    {
      id: `${GlobalConstants.MOCK_CUSTOMER_PREFIX}053`,
      name: "Backwater Central",
      address: "147 Canal Road",
      city: "Alleppey",
      pincode: "688001",
      phone: "3456789016",
      route: "Route 3",
    },
    {
      id: `${GlobalConstants.MOCK_CUSTOMER_PREFIX}054`,
      name: "Alappuzha Central",
      address: "258 Market Road",
      city: "Alleppey",
      pincode: "688001",
      phone: "3456789016",
      route: "Route 3",
    },
    {
      id: `${GlobalConstants.MOCK_CUSTOMER_PREFIX}055`,
      name: "Pharma Solutions Central",
      address: "369 Medicine Lane",
      city: "Alleppey",
      pincode: "688001",
      phone: "3456789016",
      route: "Route 3",
    },
    {
      id: `${GlobalConstants.MOCK_CUSTOMER_PREFIX}056`,
      name: "Cherthala Central",
      address: "741 Main Street",
      city: "Alleppey",
      pincode: "688001",
      phone: "3456789016",
      route: "Route 3",
    },
    {
      id: `${GlobalConstants.MOCK_CUSTOMER_PREFIX}057`,
      name: "Kayamkulam Central",
      address: "852 Railway Road",
      city: "Alleppey",
      pincode: "688001",
      phone: "3456789016",
      route: "Route 3",
    },
    {
      id: `${GlobalConstants.MOCK_CUSTOMER_PREFIX}058`,
      name: "Haripad Central",
      address: "963 Temple Road",
      city: "Alleppey",
      pincode: "688001",
      phone: "3456789016",
      route: "Route 3",
    },
    {
      id: `${GlobalConstants.MOCK_CUSTOMER_PREFIX}059`,
      name: "Mavelikkara Central",
      address: "147 Market Street",
      city: "Alleppey",
      pincode: "688001",
      phone: "3456789016",
      route: "Route 3",
    },
    {
      id: `${GlobalConstants.MOCK_CUSTOMER_PREFIX}060`,
      name: "Chengannur Central",
      address: "258 Bus Stand Road",
      city: "Alleppey",
      pincode: "688001",
      phone: "3456789016",
      route: "Route 3",
    },

    // Route 4 - Vaikom & Kottayam
    {
      id: `${GlobalConstants.MOCK_CUSTOMER_PREFIX}061`,
      name: "Care Hospital",
      address: "987 Treatment Blvd",
      city: "Vaikom",
      pincode: "686141",
      phone: "5678901238",
      route: "Route 4",
    },
    {
      id: `${GlobalConstants.MOCK_CUSTOMER_PREFIX}062`,
      name: "Vaikom Medical Store",
      address: "123 Temple Road",
      city: "Vaikom",
      pincode: "686141",
      phone: "5678901238",
      route: "Route 4",
    },
    {
      id: `${GlobalConstants.MOCK_CUSTOMER_PREFIX}063`,
      name: "Life Sciences Co",
      address: "147 Research Drive",
      city: "Kottayam",
      pincode: "686001",
      phone: "1234567895",
      route: "Route 4",
    },
    {
      id: `${GlobalConstants.MOCK_CUSTOMER_PREFIX}064`,
      name: "Kottayam Medical College",
      address: "456 College Road",
      city: "Kottayam",
      pincode: "686001",
      phone: "1234567895",
      route: "Route 4",
    },
    {
      id: `${GlobalConstants.MOCK_CUSTOMER_PREFIX}065`,
      name: "Changanassery Hospital",
      address: "789 Main Road",
      city: "Kottayam",
      pincode: "686001",
      phone: "1234567895",
      route: "Route 4",
    },
    {
      id: `${GlobalConstants.MOCK_CUSTOMER_PREFIX}066`,
      name: "Pala Medical Center",
      address: "321 Market Street",
      city: "Kottayam",
      pincode: "686001",
      phone: "1234567895",
      route: "Route 4",
    },
    {
      id: `${GlobalConstants.MOCK_CUSTOMER_PREFIX}067`,
      name: "Kanjirapally Clinic",
      address: "654 Railway Road",
      city: "Kottayam",
      pincode: "686001",
      phone: "1234567895",
      route: "Route 4",
    },
    {
      id: `${GlobalConstants.MOCK_CUSTOMER_PREFIX}068`,
      name: "Erattupetta Pharmacy",
      address: "987 Bus Stand",
      city: "Kottayam",
      pincode: "686001",
      phone: "1234567895",
      route: "Route 4",
    },
    {
      id: `${GlobalConstants.MOCK_CUSTOMER_PREFIX}069`,
      name: "Mundakayam Health Center",
      address: "147 Hill Station Road",
      city: "Kottayam",
      pincode: "686001",
      phone: "1234567895",
      route: "Route 4",
    },
    {
      id: `${GlobalConstants.MOCK_CUSTOMER_PREFIX}070`,
      name: "Kumarakom Medical Store",
      address: "258 Backwater Road",
      city: "Kottayam",
      pincode: "686001",
      phone: "1234567895",
      route: "Route 4",
    },
    {
      id: `${GlobalConstants.MOCK_CUSTOMER_PREFIX}071`,
      name: "Care Central Hospital",
      address: "852 Treatment Blvd",
      city: "Vaikom",
      pincode: "686141",
      phone: "5678901238",
      route: "Route 4",
    },
    {
      id: `${GlobalConstants.MOCK_CUSTOMER_PREFIX}072`,
      name: "Vaikom Central Medical",
      address: "963 Temple Road",
      city: "Vaikom",
      pincode: "686141",
      phone: "5678901238",
      route: "Route 4",
    },
    {
      id: `${GlobalConstants.MOCK_CUSTOMER_PREFIX}073`,
      name: "Life Sciences Central",
      address: "147 Research Drive",
      city: "Kottayam",
      pincode: "686001",
      phone: "1234567895",
      route: "Route 4",
    },
    {
      id: `${GlobalConstants.MOCK_CUSTOMER_PREFIX}074`,
      name: "Kottayam Central College",
      address: "258 College Road",
      city: "Kottayam",
      pincode: "686001",
      phone: "1234567895",
      route: "Route 4",
    },
    {
      id: `${GlobalConstants.MOCK_CUSTOMER_PREFIX}075`,
      name: "Changanassery Central",
      address: "369 Main Road",
      city: "Kottayam",
      pincode: "686001",
      phone: "1234567895",
      route: "Route 4",
    },
    {
      id: `${GlobalConstants.MOCK_CUSTOMER_PREFIX}076`,
      name: "Pala Central Medical",
      address: "741 Market Street",
      city: "Kottayam",
      pincode: "686001",
      phone: "1234567895",
      route: "Route 4",
    },
    {
      id: `${GlobalConstants.MOCK_CUSTOMER_PREFIX}077`,
      name: "Kanjirapally Central",
      address: "852 Railway Road",
      city: "Kottayam",
      pincode: "686001",
      phone: "1234567895",
      route: "Route 4",
    },
    {
      id: `${GlobalConstants.MOCK_CUSTOMER_PREFIX}078`,
      name: "Erattupetta Central",
      address: "963 Bus Stand",
      city: "Kottayam",
      pincode: "686001",
      phone: "1234567895",
      route: "Route 4",
    },
    {
      id: `${GlobalConstants.MOCK_CUSTOMER_PREFIX}079`,
      name: "Mundakayam Central",
      address: "147 Hill Station Road",
      city: "Kottayam",
      pincode: "686001",
      phone: "1234567895",
      route: "Route 4",
    },
    {
      id: `${GlobalConstants.MOCK_CUSTOMER_PREFIX}080`,
      name: "Kumarakom Central",
      address: "258 Backwater Road",
      city: "Kottayam",
      pincode: "686001",
      phone: "1234567895",
      route: "Route 4",
    },

    // Route 5 - Idukki
    {
      id: `${GlobalConstants.MOCK_CUSTOMER_PREFIX}081`,
      name: "BioMed Corp",
      address: "258 Science Street",
      city: "Idukki",
      pincode: "685602",
      phone: "2345678906",
      route: "Route 5",
    },
    {
      id: `${GlobalConstants.MOCK_CUSTOMER_PREFIX}082`,
      name: "Idukki Medical Center",
      address: "123 Hill Station",
      city: "Idukki",
      pincode: "685602",
      phone: "2345678906",
      route: "Route 5",
    },
    {
      id: `${GlobalConstants.MOCK_CUSTOMER_PREFIX}083`,
      name: "Munnar Hospital",
      address: "456 Tea Garden Road",
      city: "Idukki",
      pincode: "685602",
      phone: "2345678906",
      route: "Route 5",
    },
    {
      id: `${GlobalConstants.MOCK_CUSTOMER_PREFIX}084`,
      name: "Thekkady Clinic",
      address: "789 Wildlife Road",
      city: "Idukki",
      pincode: "685602",
      phone: "2345678906",
      route: "Route 5",
    },
    {
      id: `${GlobalConstants.MOCK_CUSTOMER_PREFIX}085`,
      name: "Kumily Medical Store",
      address: "321 Spice Market",
      city: "Idukki",
      pincode: "685602",
      phone: "2345678906",
      route: "Route 5",
    },
    {
      id: `${GlobalConstants.MOCK_CUSTOMER_PREFIX}086`,
      name: "Vandiperiyar Pharmacy",
      address: "654 Plantation Road",
      city: "Idukki",
      pincode: "685602",
      phone: "2345678906",
      route: "Route 5",
    },
    {
      id: `${GlobalConstants.MOCK_CUSTOMER_PREFIX}087`,
      name: "Peermade Health Center",
      address: "987 Hill Road",
      city: "Idukki",
      pincode: "685602",
      phone: "2345678906",
      route: "Route 5",
    },
    {
      id: `${GlobalConstants.MOCK_CUSTOMER_PREFIX}088`,
      name: "Adimali Medical Store",
      address: "147 Valley Road",
      city: "Idukki",
      pincode: "685602",
      phone: "2345678906",
      route: "Route 5",
    },
    {
      id: `${GlobalConstants.MOCK_CUSTOMER_PREFIX}089`,
      name: "Nedumkandam Clinic",
      address: "369 Forest Road",
      city: "Idukki",
      pincode: "685602",
      phone: "2345678906",
      route: "Route 5",
    },
    {
      id: `${GlobalConstants.MOCK_CUSTOMER_PREFIX}090`,
      name: "Thodupuzha Medical Center",
      address: "741 Main Road",
      city: "Idukki",
      pincode: "685602",
      phone: "2345678906",
      route: "Route 5",
    },
    {
      id: `${GlobalConstants.MOCK_CUSTOMER_PREFIX}091`,
      name: "BioMed Central Corp",
      address: "852 Science Street",
      city: "Idukki",
      pincode: "685602",
      phone: "2345678906",
      route: "Route 5",
    },
    {
      id: `${GlobalConstants.MOCK_CUSTOMER_PREFIX}092`,
      name: "Idukki Central Medical",
      address: "963 Hill Station",
      city: "Idukki",
      pincode: "685602",
      phone: "2345678906",
      route: "Route 5",
    },
    {
      id: `${GlobalConstants.MOCK_CUSTOMER_PREFIX}093`,
      name: "Munnar Central Hospital",
      address: "147 Tea Garden Road",
      city: "Idukki",
      pincode: "685612",
      route: "Route 5",
    },
    {
      id: `${GlobalConstants.MOCK_CUSTOMER_PREFIX}094`,
      name: "Thekkady Central Clinic",
      address: "258 Wildlife Road",
      city: "Idukki",
      pincode: "685509",
      route: "Route 5",
    },
    {
      id: `${GlobalConstants.MOCK_CUSTOMER_PREFIX}095`,
      name: "Kumily Central Medical",
      address: "369 Spice Market",
      city: "Idukki",
      pincode: "685509",
      route: "Route 5",
    },
    {
      id: `${GlobalConstants.MOCK_CUSTOMER_PREFIX}096`,
      name: "Vandiperiyar Central",
      address: "741 Plantation Road",
      city: "Idukki",
      pincode: "685533",
      route: "Route 5",
    },
    {
      id: `${GlobalConstants.MOCK_CUSTOMER_PREFIX}097`,
      name: "Peermade Central",
      address: "852 Hill Road",
      city: "Idukki",
      pincode: "685531",
      route: "Route 5",
    },
    {
      id: `${GlobalConstants.MOCK_CUSTOMER_PREFIX}098`,
      name: "Adimali Central",
      address: "963 Valley Road",
      city: "Idukki",
      pincode: "685561",
      route: "Route 5",
    },
    {
      id: `${GlobalConstants.MOCK_CUSTOMER_PREFIX}099`,
      name: "Nedumkandam Central",
      address: "147 Forest Road",
      city: "Idukki",
      pincode: "685553",
      route: "Route 5",
    },
    {
      id: `${GlobalConstants.MOCK_CUSTOMER_PREFIX}100`,
      name: "Thodupuzha Central",
      address: "258 Main Road",
      city: "Idukki",
      pincode: "685602",
      phone: "2345678906",
      route: "Route 5",
    },
  ];
}
